swagger: "2.0"
info:
  description: "Test API"
  version: "1.0.0"
  title: "test API"
host: "localhost"
schemes:
  - "http"
paths:
  /mypath1:
    $ref: paths/mypath1.yml
  /mypath2:
    $ref: paths/mypath2.yml
